prompts = [
    "Faceshot Portrait of pretty young (18-year-old) Caucasian wearing a high neck sweater, (masterpiece, extremely detailed skin, photorealistic, heavy shadow, dramatic and cinematic lighting, key light, fill light), sharp focus, BREAK epicrealism",
    "Upper body portrait of a young man with short black hair wearing a blue shirt.",
    "Upper body shot of a woman with long blonde hair in a red dress.",
    "Half-body portrait of a teenager with curly brown hair and a green sweater.",
    "Upper body image of a man with a beard and a black leather jacket.",
    "Upper body photo of a woman with short gray hair wearing a white blouse.",
    "Upper body portrait of a young girl with braided hair in a pink top.",
    "Upper body shot of a man with a mustache and a striped shirt.",
    "Half-body portrait of a woman with long black hair and a purple scarf.",
    "Upper body image of a teenager with a crew cut and a navy blue hoodie.",
    "Upper body photo of a woman with shoulder-length hair in a floral blouse.",
    "Upper body portrait of a young man with a goatee and a gray suit.",
    "Upper body shot of a woman with wavy hair and a yellow sundress.",
    "Half-body portrait of a teenager with a pixie cut and a black tank top.",
    "Upper body image of a man with a bald head and a brown leather jacket.",
    "Upper body photo of a woman with long red hair wearing a silver necklace and a white shirt.",
    "Upper body portrait of a young girl with curly hair and a denim jacket.",
    "Upper body shot of a man with a receding hairline and a plaid shirt.",
    "Half-body portrait of a woman with short brown hair and a gold bracelet.",
    "Upper body image of a teenager with a mohawk and a black leather jacket.",
    "Upper body photo of a woman with long straight hair in a turquoise blouse.",
    "Upper body portrait of a young man with a beard and a red tie.",
    "Upper body shot of a woman with curly hair and a pair of sunglasses.",
    "Half-body portrait of a teenager with a bob cut and a pink sweater.",
    "Upper body image of a man with a mustache and a green flannel shirt.",
    "Upper body photo of a woman with short black hair wearing a black leather jacket.",
    "Upper body portrait of a young girl with a ponytail and a purple dress.",
    "Upper body shot of a man with a goatee and a blue button-down shirt.",
    "Half-body portrait of a woman with wavy hair and a pair of earrings.",
    "Upper body image of a teenager with a shaved head and a gray hoodie.",
    "Upper body photo of a woman with long blonde hair wearing a gold necklace and a white blouse.",
    "Upper body portrait of a young man with a crew cut and a black suit.",
    "Upper body shot of a woman with short gray hair and a red scarf.",
    "Half-body portrait of a teenager with curly brown hair and a green tank top.",
    "Upper body image of a man with a beard and a brown leather jacket.",
    "Upper body photo of a woman with shoulder-length hair in a floral dress.",
    "Upper body portrait of a young girl with braided hair and a pink sundress.",
    "Upper body shot of a man with a mustache and a striped tie.",
    "Half-body portrait of a woman with long black hair and a purple scarf.",
    "Upper body image of a teenager with a crew cut and a navy blue shirt.",
    "Upper body photo of a woman with short gray hair wearing a white blouse and a gold bracelet.",
    "Upper body portrait of a young man with a goatee and a gray suit jacket.",
    "Upper body shot of a woman with wavy hair and a yellow blouse.",
    "Half-body portrait of a teenager with a pixie cut and a black leather jacket.",
    "Upper body image of a man with a bald head and a brown flannel shirt.",
    "Upper body photo of a woman with long red hair wearing a silver necklace and a turquoise blouse.",
    "Upper body portrait of a young girl with curly hair and a denim jacket.",
    "Upper body shot of a man with a receding hairline and a plaid tie.",
    "Half-body portrait of a woman with short brown hair and a gold bracelet.",
    "Upper body image of a teenager with a mohawk and a black hoodie.",
    "Upper body photo of a woman with long straight hair in a white shirt and a pair of sunglasses.",
    "Upper body portrait of a young man with a beard and a red shirt.",
    "Upper body shot of a woman with curly hair and a pair of earrings.",
    "Half-body portrait of a teenager with a bob cut and a pink sweater.",
    "Upper body image of a man with a mustache and a green button-down shirt.",
    "Upper body photo of a woman with short black hair wearing a black leather jacket.",
    "Upper body portrait of a young girl with a ponytail and a purple dress.",
    "Upper body shot of a man with a goatee and a blue tie.",
    "Half-body portrait of a woman with wavy hair and a red scarf.",
    "Upper body image of a teenager with a shaved head and a gray shirt.",
    "Upper body photo of a woman with long blonde hair wearing a gold necklace and a white blouse.",
    "Upper body portrait of a young man with a crew cut and a black suit.",
    "Upper body shot of a woman with short gray hair and a red scarf.",
    "Half-body portrait of a teenager with curly brown hair and a green tank top.",
    "Upper body image of a man with a beard and a brown leather jacket.",
    "Upper body photo of a woman with shoulder-length hair in a floral dress.",
    "Upper body portrait of a young girl with braided hair and a pink sundress.",
    "Upper body shot of a man with a mustache and a striped tie.",
    "Half-body portrait of a woman with long black hair and a purple scarf.",
    "Upper body image of a teenager with a crew cut and a navy blue shirt.",
    "Upper body photo of a woman with short gray hair wearing a white blouse and a gold bracelet.",
    "Upper body portrait of a young man with a goatee and a gray suit jacket.",
    "Upper body shot of a woman with wavy hair and a yellow blouse.",
    "Half-body portrait of a teenager with a pixie cut and a black leather jacket.",
    "Upper body image of a man with a bald head and a brown flannel shirt.",
    "Upper body photo of a woman with long red hair wearing a silver necklace and a turquoise blouse.",
    "Upper body portrait of a young girl with curly hair and a denim jacket.",
    "Upper body shot of a man with a receding hairline and a plaid tie.",
    "Half-body portrait of a woman with short brown hair and a gold bracelet.",
    "Upper body image of a teenager with a mohawk and a black hoodie.",
    "Upper body photo of a woman with long straight hair in a white shirt and a pair of sunglasses.",
    "Upper body portrait of a young man with a beard and a red shirt.",
    "Upper body shot of a woman with curly hair and a pair of earrings.",
    "Half-body portrait of a teenager with a bob cut and a pink sweater.",
    "Upper body image of a man with a mustache and a green button-down shirt.",
    "Upper body photo of a woman with short black hair wearing a black leather jacket.",
    "Upper body portrait of a young girl with a ponytail and a purple dress.",
    "Upper body shot of a man with a goatee and a blue tie.",
    "Half-body portrait of a woman with wavy hair and a red scarf.",
    "Upper body image of a teenager with a shaved head and a gray shirt.",
    "Upper body photo of a woman with long blonde hair wearing a gold necklace and a white blouse.",
    "Upper body portrait of a young man with a crew cut and a black suit.",
    "Upper body shot of a woman with short gray hair and a red scarf.",
    "Half-body portrait of a teenager with curly brown hair and a green tank top.",
    "Upper body image of a man with a beard and a brown leather jacket.",
    "Upper body photo of a woman with shoulder-length hair in a floral dress.",
    "Upper body portrait of a young girl with braided hair and a pink sundress.",
    "Upper body shot of a man with a mustache and a striped tie.",
    "Half-body portrait of a woman with long black hair and a purple scarf.",
    "Upper body image of a teenager with a crew cut and a navy blue shirt.",
    "Upper body photo of a woman with short gray hair wearing a white blouse and a gold bracelet.",
    "Upper body portrait of a young man with a goatee and a gray suit jacket.",
    "Upper body shot of a woman with wavy hair and a yellow blouse.",
    "Half-body portrait of a teenager with a pixie cut and a black leather jacket.",
    "Upper body image of a man with a bald head and a brown flannel shirt.",
    "Upper body photo of a woman with long red hair wearing a silver necklace and a turquoise blouse.",
    "Upper body portrait of a young girl with curly hair and a denim jacket.",
    "Upper body shot of a man with a receding hairline and a plaid tie.",
    "Half-body portrait of a woman with short brown hair and a gold bracelet.",
    "Upper body image of a teenager with a mohawk and a black hoodie.",
]

neg_prompt = "poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"